apiVersion: v1
kind: List
items:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    spec:
      template:
        metadata:
          labels:
            name: navigation
            appId: 2aa91m8p213d
        spec:
          containers:
            - image: >-
                image-registry.openshift-image-registry.svc:5000/cmolloy/navigation
    metadata:
      name: navigation
      namespace: cmolloy
